### ISSUE TITLE
RuntimeError: Found 0 files in subfolders of: dataset\selfie2anime\trainA ?

### ISSUE THREAD

**Issue by danerlt** [znxlwm/UGATIT-pytorch#19]
Hi, when I execute `python main.py --dataset selfie2anime` ,it tips RuntimeError:
```
number of epochs must be larger than or equal to one

##### Information #####
# light :  False
# dataset :  selfie2anime
# batch_size :  1
# iteration per epoch :  1000000

##### Generator #####
# residual blocks :  4

##### Discriminator #####
# discriminator layer :  6

##### Weight #####
# adv_weight :  1
# cycle_weight :  10
# identity_weight :  10
# cam_weight :  1000
Traceback (most recent call last):
  File "main.py", line 83, in <module>
    main()
  File "main.py", line 72, in main
    gan.build_model()
  File "H:\workspace\UGATIT-pytorch\UGATIT.py", line 100, in build_model
    self.trainA = ImageFolder(os.path.join('dataset', self.dataset, 'trainA'), train_transform)
  File "H:\workspace\UGATIT-pytorch\dataset.py", line 107, in __init__
    target_transform=target_transform)
  File "H:\workspace\UGATIT-pytorch\dataset.py", line 47, in __init__
    "Supported extensions are: " + ",".join(extensions)))
RuntimeError: Found 0 files in subfolders of: dataset\selfie2anime\trainA
Supported extensions are: .jpg,.jpeg,.png,.ppm,.bmp,.pgm,.tif
```
but this folder hava default female_2321.jpg file
![image](https://user-images.githubusercontent.com/14197717/62698062-cfcae580-ba0e-11e9-8fbe-900e0e6a6e34.png)

**Comment by hitechbeijing** [comment]
trainA目录放selife数据，trainB放animeface数据，我用中文回答算了。反正你看的懂。

**Comment by danerlt** [comment]
@hitechbeijing 自己放数据进去跑吗？

**Comment by hitechbeijing** [comment]
> @hitechbeijing 自己放数据进去跑吗？

作者给你的只是个示例，注意看使用说明。

**Comment by danerlt** [comment]
好的 我再研究研究 谢谢！
